# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
